server:
  port: 9935
  
spring:  mvc:    view:      prefix: /views/
      suffix: .jsp
  datasource:    url: jdbc:h2:mem:UserDB
    driver-class-name: org.h2.Driver
    username: user

  jpa:    database-platform: org.hibernate.dialect.H2Dialect    properties:
      hibernate:        show-sql: true
        format_sql: true
    
  h2:    console:      enabled: true
      path: /h2