server:
  port: 9935
  
spring:  mvc:    view:      prefix: /views/
      suffix: .jsp
  datasource:    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: user
    password:   jpa:    database-platform: org.hibernate.dialect.H2Dialect            